version: 2

# -- templates --------------

aliases:
  - &attach_workspace
      attach_workspace:
        at: .

  - &configure_debian
      run:
        name: Configure debian environment
        command: |
          # remove apt repos we don't use
          pushd /etc/apt/sources.list.d
          rm -v cernvm.list cvmfs-contrib.list
          # install git and ssh
          apt-get -yqq update
          apt-get -yqq install -y git ssh

  - &configure_rhel
      run:
        name: Configure RHEL environment
        command: |
          # install git and ssh
          yum -y -q update
          yum -y -q install git openssh-clients

  - &set_python_environment
      run:
        name: Set Python environment
        command: |
          export PIP_FLAGS=${PIP_FLAGS:-"--progress-bar=off"}
          echo "export PIP_FLAGS=\"${PIP_FLAGS}\"" >> ${BASH_ENV}
          echo "Set PIP_FLAGS=\"${PIP_FLAGS}\""
          export PYTHON_VERSION=${CIRCLE_JOB##*:}
          echo "export PYTHON_VERSION=\"${PYTHON_VERSION}\"" >> ${BASH_ENV}
          echo "Set PYTHON_VERSION=\"${PYTHON_VERSION}\""

  - &run-tests
      run:
        name: Test
        command: bash -ex ci/test.sh

  - &codecov
      run:
        name: Submit coverage to codecov
        command: bash -ex ci/codecov.sh

  - &coveralls
      run:
        name: Submit coverage to coveralls
        command: bash -ex ci/coveralls.sh

  - &store_test_results
      store_test_results:
        path: tests

  - &store_test_artifacts
      store_artifacts:
        path: tests

  - &python-build
      docker:
        - image: python
      steps:
        - checkout
        - *attach_workspace
        - *set_python_environment
        - run:
            name: Install
            command: python -m pip install ${PIP_FLAGS} gwpy-*.tar.*
        - *run-tests
        - *codecov
        - store_test_results:
            path: tests
        - store_artifacts:
            path: tests

  - &conda-build
      docker:
        - image: continuumio/miniconda3
      steps:
        - checkout
        - *attach_workspace
        - restore_cache:
            key: v6-gwpy-{{ .Environment.CIRCLE_JOB }}
        - *set_python_environment
        - run:
            name: Install
            command: bash -ex ci/install-conda.sh
        - *run-tests
        - *codecov
        - save_cache:
            key: v6-gwpy-{{ .Environment.CIRCLE_JOB }}
            paths:
              - "/opt/conda/envs/gwpyci"
        - *store_test_results
        - *store_test_artifacts

  - &debian-build
      steps:
        - *configure_debian
        - checkout
        - *attach_workspace
        - *set_python_environment
        - run:
            name: Build
            command: bash -ex ci/install-debian.sh
        - *run-tests
        - *codecov
        - *store_test_results
        - *store_test_artifacts

  - &centos-build
      steps:
        - *configure_rhel
        - checkout
        - *attach_workspace
        - *set_python_environment
        - run:
            name: Build
            command: bash -ex ci/install-el.sh
        - *run-tests
        - *codecov
        - *store_test_results
        - *store_test_artifacts
        - store_artifacts:
            path: "*.rpm"

# -- jobs -------------------

jobs:
  sdist:
    docker:
      - image: python
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            set -ex
            python -m pip install "setuptools>=20.2.0" "wheel"
      - run:
          name: Build tarball
          command: python setup.py --quiet sdist --dist-dir . bdist_wheel --universal --dist-dir .
      - persist_to_workspace:
          root: .
          paths:
            - gwpy-*.tar.*
            - gwpy-*-none-any.whl

  flake8:
    docker:
      - image: python
    steps:
      - checkout
      - run:
          name: Lint
          command: |
            set -ex
            python -m pip install ${PIP_FLAGS} "flake8>=3.7.0"
            mkdir -p tests
            python -m flake8 --output-file tests/flake8.txt
      - run:
          name: Create flake8 report
          when: always
          command: |
            set -ex
            python -m pip install ${PIP_FLAGS} flake8-junit-report
            python -m junit_conversor tests/flake8.txt tests/junit.xml
      - *store_test_results
      - *store_test_artifacts

  # -- python ---------------

  python:3.5:
    <<: *python-build
    docker:
      - image: python:3.5

  python:3.6:
    <<: *python-build
    docker:
      - image: python:3.6

  python:3.7:
    <<: *python-build
    docker:
      - image: python:3.7

  # -- conda ----------------

  conda:3.6:
    <<: *conda-build

  conda:3.7:
    <<: *conda-build

  # -- debian ---------------

  debian:stretch:3.5:
    <<: *debian-build
    docker:
      - image: igwn/base:stretch
    environment:
      PIP_FLAGS: " "

  # -- rhel -----------------

  el7:3.6:
    <<: *centos-build
    docker:
      - image: igwn/base:el7
    environment:
      PIP_FLAGS: " "

# -- workflow ---------------

workflows:
  version: 2
  build-and-test:
    jobs:
      - sdist
      - flake8

      # basic tests with minimal dependencies
      - python:3.5:
          requires:
            - sdist
      - python:3.6:
          requires:
            - sdist
      - python:3.7:
          requires:
            - sdist

      # conda tests
      - conda:3.6:
          requires:
            - python:3.6
      - conda:3.7:
          requires:
            - python:3.7

      # LDG reference OS tests
      - debian:stretch:3.5:
          requires:
            - sdist
      - el7:3.6:
          requires:
            - sdist
